#!/bin/bash
## A simple script to generate the skeleton for a new BukkitMod plugin.
## Written by: Pezmc

# OS Detection
## Check if we're running windows. If so, clear the
## "bash: warning: could not find /tmp, please create!
## error that likely occurred when bash was started.
if [ $_OS -a $_OS == "NT" ]; then
	_OS='nt'
else
	# Get the OS name and lowercase it.
	_OS=`uname -s | tr '[A-Z]' '[a-z]'`
	
	# Now test if it's Linux or Mac OSX
	if [[ $_OS == *linux* ]]; then
		_OS='linux'
	elif [[ $_OS == *cygwin* ]]; then
		_OS='nt'
	elif [[ $_OS == *darwin* ]]; then
		_OS='mac'
	fi
fi

# Set up the ANSI escape colors depending on OS.
if [[ $_OS == 'linux' || $_OS == 'nt' ]]; then
	# Standard ANSI escape codes.
	c_default='\e[0;37m'
	c_white='\e[1;37m'
	c_cyan='\e[1;36m'
	c_green='\e[1;32m'
	c_red='\e[0;31m'
	c_blue='\e[1;34m'
	c_yellow='\e[1;33m'
elif [[ $_OS == 'mac' ]]; then
	# For Mac OS X, we have to do it slightly
	# different.
	c_default='\033[0;37m'
	c_white='\033[1;37m'
	c_cyan='\033[1;36m'
	c_green='\033[1;32m'
	c_red='\033[0;31m'
	c_blue='\033[1;34m'
	c_yellow='\033[1;33m'
fi

# List of IDEs supported by project generation
IDE_LIST=( Ant Eclipse IntelliJ Netbeans )

# Set up the configuration file, either via a default mode or interactive mode.
# @param $1 The absolute path of the configuration file.
function configure() {
	# Grab configuration path
	cfgPath=$1
	
	# Give the user the option to configure their preferences
	if [ -z "$use_config" ]; then
		prompt="\n${c_cyan}No ${c_green}config ${c_cyan}file found. Would you like to configure the system? (Y/N): ${c_default}"
		yes_no config "$prompt"
	else
		config=1
		echo
	fi
	
	if [ $config == 1 ]; then
		# Start configuration process
		# Ask for output_path. Default to "."
		echo -ne "${c_cyan}Where would you like to put the source files? (Default: \".\"): ${c_default}"
		read output_folder
		if [ -z "$output_folder" ]; then
			output_folder="."
		fi
		
		# Ask for username
		prompt="${c_cyan}Author's Username (only letters and numbers):${c_default} "
		error="${c_red}Error: ${c_white}The username can only be made up of letters and numbers.${c_default}"
		validation_loop author_username "$prompt" "$error" 0 1 0
		
		# Ask for namespace.
		prompt="${c_cyan}Author's Namespace (usually com.domain.username):${c_default} "
		error="${c_red}Error: ${c_white}A namespace can only be made up of letters, numbers, \".\" and \"-\".${c_default}"
		bukkit_error="${c_red}Error: ${c_white}You cannot use Bukkit in your namespace.${c_default}"
		while :
		do
			echo -ne "$prompt"
			read author_namespace
			author_namespace=$(echo $author_namespace | tr '[A-Z]' '[a-z]')
			# Check for a valid namespace
			# TODO: Create a better regular expression for this
			if [[ "$author_namespace" =~ [A-Za-z0-9\.\-]+ ]]; then
				# Check for use of the Bukkit name
				if [[ $author_namespace == *org.bukkit* || $author_namespace == *com.bukkit* || $author_namespace == *net.bukkit* ]]; then
					echo -e "$bukkit_error"
				else
					if [ "$author_namespace" == "$BASH_REMATCH" ]; then
						# Remove trailing period from edge case
						if [ "${author_namespace:(-1)}" == "." ]; then
							author_namespace="${author_namespace%\.}"
						fi
						break
					else
						echo -e "$error"
					fi
				fi
			fi
		done
		
		# Ask for user input for config for each IDE. Loop until yes or no.
		for ide in ${IDE_LIST[@]} ;
		do
			set $ide;
			local gen_var="gen_$(echo $ide | tr '[A-Z]' '[a-z]')"
			yes_no $gen_var "${c_cyan}Would you like to build a project for $ide? (Y/N): ${c_default}"
		done
		
		# Write configured file
		write_config $cfgPath
		
	else
		# If they don't want to configure their preferences, write a default
		# config with all IDEs set to false
		echo -e "\n${c_cyan}Creating ${c_green}default config${c_cyan}...${c_default}" >&2
		output_folder="\".\""
		for ide in ${IDE_LIST[@]} ;
		do
			set $ide;
			local gen_var="\$gen_$(echo $ide | tr '[A-Z]' '[a-z]')"
			eval ${gen_var#$}=0
		done
		write_config $cfgPath
		source $cfgPath
	fi
	
	echo
}

# Pause (Getch)
function pause(){
	read -p "Press any key to continue..."
}

# Print the status of project generation generically
# @param $1 A string representation of the IDE to check.
# @param $2 The setting pulled from the configuration file for the IDE.
function print_generation() {
	local str_ide="$1"
	local gen="$2"
	echo -ne "    ${str_ide}${c_default}: " >&2
	if [ $gen == 1 ]; then
		echo -e "${c_green}True${c_default}" >&2
	else
		echo -e "${c_red}False${c_default}" >&2
	fi
}

# Read Configuration Files
function read_config(){
	local cfgPath="$(pwd)/settings.cfg"
	if [ -a $cfgPath ]; then
		# There was a config file present, so output its preferences
		echo -e "\n${c_cyan}Reading ${c_green}config${c_cyan}...${c_default}"
		source $cfgPath
		echo -e "  ${c_cyan}Creating IDE-specific projects:${c_default}"
		for ide in ${IDE_LIST[@]} ;
		do
			set $ide;
			local gen_var="\$gen_$(echo $ide | tr '[A-Z]' '[a-z]')"
			eval gen_var=$gen_var
			print_generation $ide $gen_var
		done
		echo -e "  ${c_cyan}Output Folder:${c_green} \"$output_folder\" ${c_default}"
		
		if [ -n "$author_username" ]; then
			echo -e "  ${c_cyan}Author's Username:${c_green} "$author_username" ${c_default}"
		fi
		if [ -n "$author_namespace" ]; then
			echo -e "  ${c_cyan}Author's Namespace:${c_green} "$author_namespace" ${c_default}"
		fi
		
		echo
		
		yes_no use_config "Do you want to use this configuration? (Y/N): "
		if [ $use_config == 0 ]; then
			configure "$cfgPath"
		fi
	else
		configure "$cfgPath"
	fi
	
	return
}

# Write a config file
# @param $1 The absolute path to the configuration file.
function write_config() {
	local cfgFile=$1
	echo "# General Settings" > $cfgFile
	echo "output_folder=$output_folder" >> $cfgFile
	echo "author_username=$author_username" >> $cfgFile
	echo "author_namespace=$author_namespace" >> $cfgFile

	echo -e "\n# Project File Generation" >> $cfgFile

	for ide in ${IDE_LIST[@]} ;
	do
		set $ide;
		local gen_var="\$gen_$(echo $ide | tr '[A-Z]' '[a-z]')"
		local gen_val=$gen_var
		eval gen_val=$gen_val
		echo -e "${gen_var#$}=$gen_val" >> $cfgFile
	done
}

# Input validation.
function validate_input(){
	local _true=1; local _false=0
	# Get the input.
	local _input=${1}
	# Same as above, but with
	# dashes and underscores.
	local _symbols=${2:-$_true}
	# Unless stated otherwise,
	# numbers will be allowed.
	local _numbers=${3:-$_true}
	# Finally, anything
	local _anything=${4:-$_false}
	if [ $_anything == $_true ]; then
		is_valid=$_true
		return
	fi
	# Escape some characters in the actual value.
	local _action=${_input//\$/\\\$}
	_action=${_action/\"/}
	
	# Begin assembling the expression.
	local _expr="sed -e 's/[a-zA-Z"
	
	## If we allow numbers, add them in.
	if [ $_numbers == $_true ]; then
		_expr="${_expr}0-9"
	fi
	
	## If we allow symbols, add them in.
	if [ $_symbols == $_true ]; then
		_expr="${_expr}_-"
	fi
	
	# Finish it off.
	_expr="${_expr}]//g'"
	
	# Now put it all together.
	local _result=""
	eval "_result=\$(echo -ne \"${_action}\" | ${_expr})"
	is_valid=$(( ${#_result} == $_false ? $_true : $_false ))
	return
}

# A simple loop ensuring the validation of a variable
# @param $1 The variable to validate.
# @param $2 The input prompt.
# @param $3 The error message.
# @param $4 Flag controlling allowance of dashes and underscores.
# @param $5 Flag controlling allowance of numbers.
# @param $6 Flag toggling validation off (i.e. allowing anything).
function validation_loop() {
	while :
	do
		local __resultvar=$1
		local _result
		echo -ne "$2"; read _result
		validate_input "$_result" $4 $5 $6
		if [ $is_valid == 1 ]; then
			break
		fi
		echo -e "$3"
	done
	eval $__resultvar="'$_result'"
	is_valid=0
}

# A simple looping yes/no dialog
# @param $1 The variable to write
# @param $2 The prompt to display
function yes_no() {
	local __resultvar=$1
	local _result
	echo -ne "$2"
	read _result; _result=$(echo $_result | tr '[A-Z]' '[a-z]')
	while :
	do
		if [ "$_result" == "y" -o "$_result" == "n" ]; then
			break;
		fi
		echo -n "Input not recognized. Please enter Y or N: "
		read _result; _result=$(echo $_result | tr '[A-Z]' '[a-z]')
	done
	
	if [ "$_result" == "y" ]; then
		_result=1
	else
		_result=0
	fi
	eval $__resultvar="'$_result'"
}

# Our banner.
echo -ne "${c_cyan} ___   _     _     _     _  _____ \n| |_) | | | | |_/ | |_/ | |  | |  \n|_|_) \\_\\_/ |_| \\ |_| \\ |_|  |_|  \n\n"
echo -ne "${c_white} __    ____  _      ____  ___    __   _____  ___   ___  \n/ /\`_ | |_  | |\\ | | |_  | |_)  / /\\   | |  / / \\ | |_) \n\\_\\_/ |_|__ |_| \\| |_|__ |_| \\ /_/--\\  |_|  \\_\\_/ |_| \\ \n\n"

# Read in our configuration.
read_config

# Get and validate user name
if [ -z "$author_username" ]; then
	prompt="\n${c_cyan}Author's Username (only letters and numbers):${c_default} "
	error="${c_red}Error: ${c_white}The username can only be made up of letters and numbers.${c_default}"
	validation_loop author_username "$prompt" "$error" 0 1 0
fi

# Get and validate plugin name
prompt="${c_cyan}Plugin's name:${c_default} "
error="${c_red}Error: ${c_white}The plugin's name can only be made up of letters.${c_default}"
validation_loop PLUGINNAME "$prompt" "$error" 0 0 0 # Disallow numbers and symbols

# Get and validate the version
prompt="${c_cyan}Plugin Version (${c_default}0.1${c_cyan} by default):${c_default} "
echo -ne "$prompt"; read PLUGINVERSION
PLUGINVERSION=${PLUGINVERSION:-0.1}
validate_input "$PLUGINVERSION" 1 1 1 # Put whatever you want here.
if [ $is_valid == 0 ]; then
	PLUGINVERSION="0.1"
fi

# Set the filenames and paths.
echo -e "${c_cyan}Generating  ${c_green}manifest${c_cyan}..

${c_white}Plugin: ${c_green}${PLUGINNAME}
${c_white}Version: ${c_blue}${PLUGINVERSION}
${c_white}Author: ${c_yellow}${author_username}${c_default}
"
BLOCKLISTENER=BlockListener.java
YBLOCKLISTENER=${PLUGINNAME}BlockListener.java
PLAYERLISTENER=PlayerListener.java
YPLAYERLISTENER=${PLUGINNAME}PlayerListener.java 
PLUGIN=YPlugin.java
YPLUGIN="${PLUGINNAME}.java"
BINPATH="${output_folder}/${PLUGINNAME}/bin"
BASEPATH="${output_folder}/${PLUGINNAME}/src"
if [ -z "$author_namespace" ]; then
	ENDPATH="${output_folder}/${PLUGINNAME}/src/${author_username}/${PLUGINNAME}"
else
	namespace=${author_namespace//./\/}
	ENDPATH="${output_folder}/${PLUGINNAME}/src/${namespace}/${PLUGINNAME}"
fi

# Create the output directories.
mkdir -p "${ENDPATH}"
mkdir -p "${BINPATH}"

# Store our current path, then enter the output area.
SCRIPTROOT=`pwd`
BASEPATH="${SCRIPTROOT}/${PLUGINNAME}"

# Create our plugin's YAML file.
cd "${BASEPATH}/src"
if [ -z "$author_namespace" ]; then
echo "name: $PLUGINNAME\n\nmain: $author_username.$PLUGINNAME\n\nversion: $PLUGINVERSION" > plugin.yml
else
echo "name: $PLUGINNAME\n\nmain: $author_namespace.$PLUGINNAME\n\nversion: $PLUGINVERSION" > plugin.yml
fi

# Inform author_username on status.
echo -e "${c_cyan}Generating ${c_green}Source Files${c_cyan}..${c_default}"

# Copy the rest of the template files.
cd "${SCRIPTROOT}"
if [ -n "$author_namespace" ]; then
	sed -e "s/<namespace>/$author_namespace/g" -e "s/<yourname>/$author_username/g" -e "s/<pluginname>/$PLUGINNAME/g" "${SCRIPTROOT}/files/${BLOCKLISTENER}" > "${ENDPATH}/$YBLOCKLISTENER"
	sed -e "s/<namespace>/$author_namespace/g" -e "s/<yourname>/$author_username/g" -e "s/<pluginname>/$PLUGINNAME/g" "${SCRIPTROOT}/files/${PLAYERLISTENER}" > "${ENDPATH}/$YPLAYERLISTENER"
	sed -e "s/<namespace>/$author_namespace/g" -e "s/<yourname>/$author_username/g" -e "s/<pluginname>/$PLUGINNAME/g" "${SCRIPTROOT}/files/${PLUGIN}" > "${ENDPATH}/${PLUGINNAME}.java"
else
	sed -e "s/<namespace>/$author_username.$PLUGINNAME/g" -e "s/<yourname>/$author_username/g" -e "s/<pluginname>/$PLUGINNAME/g" "${SCRIPTROOT}/files/${BLOCKLISTENER}" > "${ENDPATH}/$YBLOCKLISTENER"
	sed -e "s/<namespace>/$author_username.$PLUGINNAME/g" -e "s/<yourname>/$author_username/g" -e "s/<pluginname>/$PLUGINNAME/g" "${SCRIPTROOT}/files/${PLAYERLISTENER}" > "${ENDPATH}/$YPLAYERLISTENER"
	sed -e "s/<namespace>/$author_username.$PLUGINNAME/g" -e "s/<yourname>/$author_username/g" -e "s/<pluginname>/$PLUGINNAME/g" "${SCRIPTROOT}/files/${PLUGIN}" > "${ENDPATH}/${PLUGINNAME}.java"
fi

# Project file generation.

## Eclipse
if [ $gen_eclipse == 1 ]; then
	echo -e "${c_cyan}Generating ${c_green}Eclipse Project Files${c_cyan}..${c_default}"
	sed -e "s/{{PLUGINNAME}}/$PLUGINNAME/g" "${SCRIPTROOT}/projects/eclipse/.project" > "${output_folder}/${PLUGINNAME}/.project"
	cp "${SCRIPTROOT}/projects/eclipse/.classpath" "${output_folder}/${PLUGINNAME}/.classpath"
fi

## IntelliJ
if [ $gen_intellij == 1 ]; then
	echo -e "${c_cyan}Generating ${c_green}Intelli-J Project Files${c_cyan}..${c_default}"
	mkdir -p "${output_folder}/${PLUGINNAME}/.idea"
	echo -n "${PLUGINNAME}" > "${output_folder}/${PLUGINNAME}/.idea/.name"
	cp "${SCRIPTROOT}/projects/intellij/compiler.xml" "${output_folder}/${PLUGINNAME}/.idea/compiler.xml"
	cp "${SCRIPTROOT}/projects/intellij/encodings.xml" "${output_folder}/${PLUGINNAME}/.idea/encodings.xml"
	cp "${SCRIPTROOT}/projects/intellij/vcs.xml" "${output_folder}/${PLUGINNAME}/.idea/vcs.xml"
	cp "${SCRIPTROOT}/projects/intellij/project.iml" "${output_folder}/${PLUGINNAME}/${PLUGINNAME}.iml"
	sed -e "s/{{PLUGINNAME}}/$PLUGINNAME/g" "${SCRIPTROOT}/projects/intellij/modules.xml" > "${output_folder}/${PLUGINNAME}/.idea/modules.xml"
	sed -e "s/{{PLUGINNAME}}/$PLUGINNAME/g" "${SCRIPTROOT}/projects/intellij/workspace.xml" > "${output_folder}/${PLUGINNAME}/.idea/workspace.xml"
fi

## NetBeans
if [ $gen_netbeans == 1 ]; then
	echo -e "${c_cyan}Generating ${c_green}Netbeans Project Files${c_cyan}..${c_default}"
	mkdir -p "${output_folder}/${PLUGINNAME}/nbproject"
	mkdir -p "${output_folder}/${PLUGINNAME}/nbproject/private"
	cp "${SCRIPTROOT}/projects/netbeans/genfiles.properties" "${output_folder}/${PLUGINNAME}/nbproject/genfiles.properties"
	cp "${SCRIPTROOT}/projects/netbeans/private/private.properties" "${output_folder}/${PLUGINNAME}/nbproject/private/private.properties"
	sed -e "s/{{author_username}}/$author_username/g" -e "s/{{PLUGINNAME}}/$PLUGINNAME/g" "${SCRIPTROOT}/projects/netbeans/project.properties" > "${output_folder}/${PLUGINNAME}/nbproject/project.properties"
	sed -e "s/{{PLUGINNAME}}/$PLUGINNAME/g" "${SCRIPTROOT}/projects/netbeans/build-impl.xml" > "${output_folder}/${PLUGINNAME}/nbproject/build-impl.xml"
	sed -e "s/{{PLUGINNAME}}/$PLUGINNAME/g" "${SCRIPTROOT}/projects/netbeans/project.xml" > "${output_folder}/${PLUGINNAME}/nbproject/project.xml"
fi

## Apache Ant
if [ $gen_ant == 1 ]; then
	echo -e "${c_cyan}Generating ${c_green}Ant Build File${c_cyan}..${c_default}"
	sed -e "s/{{PLUGINNAME}}/$PLUGINNAME/g" "${SCRIPTROOT}/projects/ant/build.xml" > "${output_folder}/${PLUGINNAME}/build.xml"
fi

# Done
echo -e "\n${c_cyan}~~~${c_green} Done! ${c_cyan}~~~${c_default}"
echo -e "\n\n${c_yellow}NOTE: ${c_white}You will need to add a reference to wherever you keep Bukkit's jar file if you decided to generate an IDE project/build file. Look for this integrated into this script later.${c_default}\n"
if [ $_OS -a $_OS != 'nt' ]; then
	pause
fi
